# (PART) I-Débuter avec R {-}
# Introduction{#intro1} 

R est un langage de programmation créé par les staticiens [Ross Ihaka](https://en.wikipedia.org/wiki/Ross_Ihaka) et [Robert Gentleman](https://en.wikipedia.org/wiki/Robert_Gentleman_(statistician)).
C’est un langage dédié aux statistiques, représentations graphiques, ainsi que tout ce qui se rattache au traitement et manipulation de données.  C'est aussi un logiciel à accès libre (open-source) disponible sous la licence publique générale GNU ([GNU General Public License](https://en.wikipedia.org/wiki/GNU_General_Public_License
)).

Principalement écrit en [C](https://en.wikipedia.org/wiki/C_(programming_language)) et [Fortran](https://en.wikipedia.org/wiki/Fortran), R est une implémentation du langage [S](https://en.wikipedia.org/wiki/S_(programming_language)) qui supporte plusieurs paradigmes de programmation tel que :  procédural, orienté objet, fonctionnel, réflexif, impératif, tableau.

Depuis sa création, le langage a fortement évolué grâce à la contribution de sa communauté d’utilisateurs notamment par la publications de packages et de tutoriels. Cette évolution a permis d'étendre les fonctionnalités de ce langage à la rédaction d’ouvrage avec [bookdown](https://bookdown.org/), d’article et de présentations avec [R markdown](https://rmarkdown.rstudio.com/), à la représentation graphique avec [ggplot2](https://ggplot2.tidyverse.org/reference/geom_bar.html) etc.
Rien que sur le CRAN (Comprehensive R Archive Network) on peut trouver plus de 18000 packages.

Dans le chapitre suivant nous allons voir les bases de la programmation avec R en utilisant le logiciel [RStudio](https://www.rstudio.com/).


